---
title: "AmyloGraph 2.0"
description: "Expanding AmyloGraph with interacion modulators database and ML prediction models."
---

## 🧬 AmyloGraph 2.0: Taming aggregation

**Taming aggregation with AmyloGraph 2.0: a database and prediction models of amyloid self‑assembly modulators**

**PI**: Michał  
**Funding agency**: National Science Center Poland  
**Programme**: Sonata 19  
**Project ID**: 2023/51/D/NZ7/02847  
**Start date**: 10 Jul 2024  
**Duration**: 36 months  
**Budget**: 1,797,914.00 PLN (~ €423,300.00) 


Neurodegenerative diseases like Alzheimer's (~5.8 M U.S. cases in 2019, projected 13.8 M by 2050) and Parkinson's are proteinopathies marked by harmful amyloid aggregation. Existing tools, Cordax, PASTA 2.0, WALTZ, AmyloGram, predict single-protein aggregation but don’t model modulation by experimental conditions or small molecules.

AmyloGraph 1.0 cataloged amyloid–amyloid interactions, though limited to protein–protein modulators without context. The more recent aSynPEP‑DB collects peptide inhibitors of α‑synuclein aggregation, yet is constrained to peptides, inhibitors and a single target.

### 📌 Project highlights

- ➕ Expand the database to include non-protein modulators with experimental metadata  
- 🧠 Train ML models to predict aggregation modulation  
- 🧬 Build generative models for novel modulators and validate them computationally and experimentally