---
title: ""
sidebar: false
format:
  html:
    grid:
      sidebar-width: 0px
      body-width: 1500px
      margin-width: 300px
      gutter-width: 1.5rem
knitr:
  opts_chunk:
    out.width: "95%"
---

# 📝 **Bio**

------------------------------------------------------------------------




# 📱 **Contact** {#contact}

------------------------------------------------------------------------

[`r fontawesome::fa("envelope", prefer_type = "regular", fill = "pink", height = "3em")`](mailto:)
[`r fontawesome::fa("github", fill = "#24292e", height = "3em")`](https://github.com/)
[`r fontawesome::fa("orcid", fill = "#A6CE39", height = "3em")`](https://orcid.org/)
[`r fontawesome::fa("facebook", fill = "#304f85", height = "3em")`](https://www.facebook.com/)
[`r fontawesome::fa("linkedin", fill = "#0077b5", height = "3em")`](https://www.linkedin.com/in/)
[`r fontawesome::fa("twitter", fill = "#15a7ff", height = "3em")`](https://twitter.com/)
[`r fontawesome::fa("x-twitter", fill = "#24292e", height = "3em")`](https://x.com/)
[`r fontawesome::fa("steam", fill = "#2f4f4f", height = "3em")`]()
[`r fontawesome::fa("playstation", fill = "#4739aa", height = "3em")`]()

```{r, echo=FALSE, message=FALSE,include=FALSE}
source("../../R/bg_df.R")

whois <- ""
openalex_id <- ""

source("../../R/resume_fun.R")
```


# 🚀 **Research stays**

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}

research_stay(whois)

```


# 💻🧫 **Experience**

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}

work(whois)

```


# 🎓 **Education**

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}

edu_df <- education(whois)

```

`r stringr::str_flatten(edu_df$new_col)`


# 👏🏻 **Conferences, workshops** 🤝🏻 

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}

conf_work(whois)

```


#  📖 **Publications**

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}

# pubs(whois, openalex_id)

```


#  🧑🏻‍🔬 **Other activities**

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}

act_df <- other_act(whois)

```

`r stringr::str_flatten(act_df$new_col)`

