---
title: 'Krystyna (Krysia) Grzesiak'
sidebar: false
format:
  html:
    grid:
      sidebar-width: 0px
      body-width: 1500px
      margin-width: 300px
      gutter-width: 1.5rem
knitr:
  opts_chunk:
    out.width: '95%'
---
    
```{r, echo=FALSE, message=FALSE,include=FALSE}
load('../../data/bg_df_data.RData')
whois <- 'Krysia'

source('../../R/resume_fun.R')
openalex_id <- basic_info(whois)$openalex_id
library(fontawesome)
```



<!-- # 📝 **Bio** -->

<!-- ------------------------------------------------------------------------ -->

<!-- `r stringr::str_flatten(basic_info(whois)$bio)` -->

# 📱 **Contact**

------------------------------------------------------------------------

[`r fontawesome::fa('envelope', prefer_type = 'regular', fill = 'pink', height = '3em')`](mailto:krystyna.grzesiak@math.uni.wroc.pl)
[`r fontawesome::fa('github', fill = '#24292e', height = '3em')`](https://github.com/KrystynaGrzesiak)
[`r fontawesome::fa('orcid', fill = '#A6CE39', height = '3em')`](https://orcid.org/0000-0003-2581-7722)
[`r fontawesome::fa('linkedin', fill = '#0077b5', height = '3em')`](https://www.linkedin.com/in/krystyna-grzesiak-7bb290189/)
[`r fontawesome::fa('x-twitter', fill = '#24292e', height = '3em')`](https://x.com/krystyna_grz)


<!-- # 🚀 **Research stays** -->

<!-- ------------------------------------------------------------------------ -->

<!-- ```{r, echo=FALSE, message=FALSE} -->
<!-- research_stay(whois) -->
<!-- ``` -->

<!-- # 💻🧫 **Experience** -->
  
<!-- ------------------------------------------------------------------------ -->
    
<!-- ```{r, echo=FALSE, message=FALSE} -->
<!-- work(whois) -->
<!-- ``` -->

<!-- # 🎓 **Education** -->

<!-- ------------------------------------------------------------------------ -->

<!-- `r stringr::str_flatten(education(whois)$new_col)` -->

# 👏🏻 **Conferences, workshops, training schools** 🤝🏻 

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}
conf_work(whois)
```


#  📖 **Publications**

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE, error=FALSE, warning=FALSE}
pubs(whois, openalex_id)
```


<!-- # 🧑🏻‍🔬 **Other activities** -->

<!-- ------------------------------------------------------------------------ -->

<!-- `r stringr::str_flatten(other_act(whois)$new_col)` -->

