---
title: "Michał Burdukiewicz"
sidebar: false
format:
  html:
    grid:
      sidebar-width: 0px
      body-width: 1500px
      margin-width: 300px
      gutter-width: 1.5rem
---

# 📝 **Bio**

------------------------------------------------------------------------

Hi! My name is Michał Burdukiewicz and I am passionate about bioinformatics and R.

I am currently leading the Laboratory of Bioinformatics and Multi-omics Analysis at the Medical University of Białystok. Contact me if you want to collaborate with us!

My current projects:

 - [AmyloGraph](https://amylograph.com), a comprehensive database of amyloid-amyloid interactions ([doi:10.1093/nar/gkac882](https://doi.org/10.1093/nar/gkac882)).
 - [HaDeX](https://github.com/hadexversum), an integrated analytical tool for HDX-MS (maintainer [Weronika Puchała](https://github.com/werpuc)).
 - [Negative data sampling](http://biogenies.info/NegativeDatasets/), where we show that benchmarks in antimicrobial peptide prediction are biased due to the selection of negative data ([doi:10.1093/bib/bbac343](https://doi.org/10.1093/bib/bbac343)).
 
 I am also maintaining the list of [machine learning models for prediction of peptide properties](biogenies.info/peptide-prediction-list/) (see also our [article on that](https://doi.org/10.1016/j.csbj.2022.11.043)).


I ❤️ [R](https://cran.r-project.org/)!


# 📱 **Contact** {#contact}

------------------------------------------------------------------------

[`r fontawesome::fa("envelope", prefer_type = "regular", fill = "pink", height = "3em")`](mailto:michal.burdukiewicz@umb.edu.pl)
[`r fontawesome::fa("github", fill = "#24292e", height = "3em")`](https://github.com/michbur)
[`r fontawesome::fa("orcid", fill = "#A6CE39", height = "3em")`](https://orcid.org/0000-0001-8926-582X)
<!-- [`r fontawesome::fa("facebook", fill = "#304f85", height = "3em")`](https://www.facebook.com/) -->
[`r fontawesome::fa("linkedin", fill = "#0077b5", height = "3em")`](https://www.linkedin.com/in/michal-burdukiewicz/)
<!-- [`r fontawesome::fa("twitter", fill = "#15a7ff", height = "3em")`](https://twitter.com/) -->
[`r fontawesome::fa("x-twitter", fill = "#24292e", height = "3em")`](https://x.com/burdukiewicz/)
<!-- [`r fontawesome::fa("steam", fill = "#2f4f4f", height = "3em")`]() -->
<!-- [`r fontawesome::fa("playstation", fill = "#4739aa", height = "3em")`]() -->

```{r, echo=FALSE, message=FALSE,include=FALSE}
source("../../R/bg_df.R")

whois <- "Michał"
openalex_id <- "A5015968787"

source("../../R/resume_fun.R")
```


<!-- # 🚀 **Research stays** -->

<!-- ------------------------------------------------------------------------ -->

<!-- ```{r, echo=FALSE, message=FALSE} -->

<!-- research_stay(whois) -->

<!-- ``` -->


# 💻🧫 **Experience**

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}

work(whois)

```


<!-- # 🎓 **Education** -->

<!-- ------------------------------------------------------------------------ -->

```{r, echo=FALSE, message=FALSE}

edu_df <- education(whois)

```

`r stringr::str_flatten(edu_df$new_col)`


# 👏🏻 **Conferences, workshops** 🤝🏻 

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}

conf_work(whois)

```


#  📖 **Publications**

------------------------------------------------------------------------

```{r, echo=FALSE, message=FALSE}

pubs(whois, openalex_id)

```


#  🧑🏻‍🔬 **Other activities**

------------------------------------------------------------------------